import type { PublicSourceDefinition } from "./types";

export const publicSourceDefinitions = [
  {
    id: "service_public_rss",
    displayName: "Service-Public.fr RSS",
    publisherName: "Direction de l'information legale et administrative",
    description:
      "Practical administrative news and public-service updates for individuals and businesses.",
    ingestionMethod: "rss",
    discoveryUrl: "https://www.service-public.fr/abonnements/rss/actu-actualites-particuliers.rss",
    discoveryUrls: [
      "https://www.service-public.fr/abonnements/rss/actu-actualites-particuliers.rss",
      "https://www.service-public.fr/abonnements/rss/actu-actu-pro.rss",
    ],
    expectedCadence: "daily",
    averageCharsPerItem: 7651,
  },
  {
    id: "info_gouv",
    displayName: "Info.gouv.fr",
    publisherName: "Gouvernement francais",
    description: "Official Government news and explanations.",
    ingestionMethod: "rss",
    discoveryUrl: "https://www.info.gouv.fr/rss/actualites.xml",
    expectedCadence: "daily",
    averageCharsPerItem: 6578,
  },
  {
    id: "bofip_impots",
    displayName: "BOFiP / impots.gouv.fr",
    publisherName: "Direction generale des Finances publiques",
    description: "French tax doctrine updates and official tax guidance news.",
    ingestionMethod: "opendata_dataset",
    discoveryUrl: "https://bofip.impots.gouv.fr/bofip/ext/rss.xml?actualites=1&maxR=10&maxJ=14",
    contentUrl:
      "https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/bofip-vigueur/records",
    expectedCadence: "several_per_week",
    averageCharsPerItem: 1859,
  },
  {
    id: "tresor",
    displayName: "Direction generale du Tresor",
    publisherName: "Direction generale du Tresor",
    description: "Treasury publications, economic articles, and official updates.",
    ingestionMethod: "atom",
    discoveryUrl: "https://www.tresor.economie.gouv.fr/Flux/Atom/Articles/Home",
    expectedCadence: "several_per_week",
    averageCharsPerItem: 9885,
  },
  {
    id: "assemblee_nationale",
    displayName: "Assemblee nationale",
    publisherName: "Assemblee nationale",
    description: "Parliamentary communications and documents.",
    ingestionMethod: "rss",
    discoveryUrl: "https://www2.assemblee-nationale.fr/feeds/detail/documents-parlementaires",
    expectedCadence: "irregular",
    averageCharsPerItem: 4981,
  },
  {
    id: "senat_press",
    displayName: "Senat Press",
    publisherName: "Senat",
    description: "Senate press releases and official press updates.",
    ingestionMethod: "rss",
    discoveryUrl: "https://www.senat.fr/rss/presse.rss",
    expectedCadence: "several_per_week",
    averageCharsPerItem: 13048,
  },
  {
    id: "conseil_etat_actualites",
    displayName: "Conseil d'Etat Actualites",
    publisherName: "Conseil d'Etat",
    description: "News from France's supreme administrative court.",
    ingestionMethod: "rss",
    discoveryUrl: "https://www.conseil-etat.fr/rss/actualites-rss",
    expectedCadence: "weekly",
    averageCharsPerItem: 6426,
  },
] as const satisfies readonly PublicSourceDefinition[];
